image: ubuntu

services: 
- docker

environment:
  DOCKERHUB_PASS:
    secure: A66kPtpxEo0Ts8gLOnx6+y1ls7PXU8tlMZRm1ju+oio=

before_build:
  - sh: docker login --username=$DOCKERHUB_USER --password $DOCKERHUB_PASS

build_script:
  - sh: docker build -t safijari/manylinux2010-x64:latest .

deploy_script:
  - sh: docker push safijari/manylinux2010-x64

notifications:
  - provider: Email
    to:
      - $APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
    on_build_status_changed: true

